// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWul-c-PB3WjbaPnFnHACa5kiq3XjGP6A',
    appId: '1:546109117328:web:440663bf4c7945e72d9915',
    messagingSenderId: '546109117328',
    projectId: 'whatsapp--backend-44b12',
    authDomain: 'whatsapp--backend-44b12.firebaseapp.com',
    storageBucket: 'whatsapp--backend-44b12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlSz8gTjk7H16D3YOj7MCVYVCLpjYVPo',
    appId: '1:546109117328:android:6efcd32e0e7a26262d9915',
    messagingSenderId: '546109117328',
    projectId: 'whatsapp--backend-44b12',
    storageBucket: 'whatsapp--backend-44b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaNl4wMG_oKeSOsoolEcVBgLWH1KQcKio',
    appId: '1:546109117328:ios:0765805426b928262d9915',
    messagingSenderId: '546109117328',
    projectId: 'whatsapp--backend-44b12',
    storageBucket: 'whatsapp--backend-44b12.appspot.com',
    iosClientId: '546109117328-ffcnd9q965fl6iml94t3ij9joru6elq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
